version: "3.1"
services:
  code-server:
    image: lscr.io/linuxserver/code-server:latest
    ports:
        - 8443:8443
    networks:
      - traefik-swarm-network
    deploy:
      mode: replicated
      replicas: 2
      placement:
        constraints:
          - node.role==worker
          - node.labels.arch==arm64
      restart_policy:
        condition: on-failure
      labels:
        # Frontend
        - "traefik.enable=true"
        - "traefik.docker.network=traefik-swarm-network"
        - "traefik.http.routers.code-http.entrypoints=web"
        - "traefik.http.routers.code-http.rule=Host(`code-server.mcbourdeux-workstation.com`)"
        - "traefik.http.routers.code-http.middlewares=wireguard-https"
        - "traefik.http.routers.code-http.service=wireguard"
        - "traefik.http.services.code.loadbalancer.server.port=8443"
        - "traefik.http.middlewares.code-https.redirectscheme.scheme=https"
        - "traefik.http.routers.code.entrypoints=websecure"
        - "traefik.http.routers.code.rule=Host(`code-server.mcbourdeux-workstation.com`)"
        - "traefik.http.routers.code.tls=true"
        - "traefik.http.routers.code.tls.certresolver=letsencrypt"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - PASSWORD=code-server-password
      - SUDO_PASSWORD=code-server-password
      - PROXY_DOMAIN=vps2.mcbourdeux-workstation.com #optional
      - DEFAULT_WORKSPACE=/config/workspace #optional
    volumes:
      - /datacenter2/docker/code-server:/config

networks:
  traefik-swarm-network:
    external: true

secrets:
  code-server-password:
    external: true
