version: '3'

services:
  db:
    image: postgres:14-alpine
    container_name: nextcloud-db
    hostname: postgres
    networks:
      traefik-internetwork:
        ipv4_address: 172.18.0.20
    environment:
      - PUID=$PUID
      - PGID=$PGID
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - /datacenter/docker/postgres:/var/lib/postgresql/data
    restart: always
    labels:
      - com.centurylinklabs.watchtower.enable=false
      - traefik.enable=true
      - traefik.docker.network=traefik.internetwork
      - traefik.tcp.routers.postgres.entryPoints=postgres
      - traefik.tcp.routers.postgres.service=postgres
      - traefik.tcp.routers.postgres.rule=HostSNI(`*`)
      # services (needed for TCP)
      - traefik.tcp.services.postgres.loadbalancer.server.port=5432
  
  cache:
    image: redis:latest
    container_name: nextcloud-cache
    networks:
      traefik-internetwork:
        ipv4_address: 172.18.0.19
    hostname: redis
    restart: always
    command: redis-server --save 20 1 --loglevel warning
    labels:
      - com.centurylinklabs.watchtower.enable=false
    volumes: 
      - /datacenter/docker/redis:/data

  app:
    image: nextcloud:latest
    container_name: nextcloud-app
    hostname: nextcloud-app
    networks:
      traefik-internetwork:
        ipv4_address: 172.18.0.18
    environment:
      - PUID=0
      - PGID=0
      - TZ=$TZ
      - POSTGRES_DB=$POSTGRES_DB
      - POSTGRES_USER=$POSTGRES_ROOT_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_HOST=postgres:5432
      - REDIS_HOST=redis
      - REDIS_HOST_PORT=6379
      - PHP_MEMORY_LIMIT=4G
      - PHP_UPLOAD_LIMIT=15G
      - APACHE_DISABLE_REWRITE_IP=1
    volumes:
      - /datacenter/docker/nextcloud:/var/www/html:rw
      - /Ext-Onedrive:/mnt/onedrive-personal:rw
      - /datacenter/temp/nextcloud:/mnt/tmp:rw
      #- /datacenter/docker/nextcloud/php-user-config:/usr/local/etc/php/conf.d
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nextcloud-app.entrypoints=web"
      - "traefik.http.routers.nextcloud-app.rule=Host(`altt-cloud.gxcaothai.net`)"
      - "traefik.http.middlewares.https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.nextcloud-app.middlewares=https-redirect"
      - "traefik.http.routers.nextcloud-app-secure.entrypoints=websecure"
      - "traefik.http.routers.nextcloud-app-secure.rule=Host(`altt-cloud.gxcaothai.net`)"
      - "traefik.http.middlewares.nc-rep.redirectregex.regex=https://(.*)/.well-known/(card|cal)dav"
      - "traefik.http.middlewares.nc-rep.redirectregex.replacement=https://$$1/remote.php/dav/"
      - "traefik.http.middlewares.nc-rep.redirectregex.permanent=true"
      - "traefik.http.middlewares.nc-header.headers.customFrameOptionsValue=SAMEORIGIN"
      - "traefik.http.routers.nextcloud-app-secure.middlewares=nc-rep,nc-header"
      - "traefik.http.routers.nextcloud-app-secure.tls=true"
      - "traefik.http.routers.nextcloud-app-secure.tls.certresolver=letsencrypt"
      - "traefik.http.routers.nextcloud-app-secure.service=nextcloud"
      - "traefik.http.services.nextcloud.loadbalancer.server.port=80"
      - "traefik.docker.network=traefik-internetwork"

    depends_on:
      - db
      - cache
  
  cron:
    image: nextcloud:latest
    container_name: nextcloud-cron
    networks:
      traefik-internetwork:
        ipv4_address: 172.18.0.17
    restart: always
    entrypoint: /cron.sh
    environment:
      - PUID=33
      - PGID=33
    labels:
      - com.centurylinklabs.watchtower.enable=false
    volumes:
      - /datacenter/docker/nextcloud:/var/www/html
      - /datacenter/docker/nextcloud/data:/var/www/html/data
    depends_on:
      - app
      
networks:
  traefik-internetwork:
    external: true
