apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: credentials-eso
  namespace: databases
spec:
  refreshInterval: 24h
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: dragonflydb-auth-eso
    creationPolicy: Owner
    deletionPolicy: Delete
  data:
    - secretKey: auth
      remoteRef:
        key: docker-secrets
        property: dragonflydb-credentials
