[log]
mode = "console"
level = "error"

[log.console]
level = "warn"
format = "error"

[security]
admin_user = "admin"
admin_password = "{{ GRAFANA_ADMIN_PASSWORD }}"
secret_key = "{{ GRAFANA_SECRET_KEY }}"

[server]
domain = "{{ GRAFANA_URL }}"
root_url = "https://{{ GRAFANA_URL }}"

[database]
type = "postgres"
host = "{{ POSTGRES_HOST }}"
name = "grafana"
user = "grafana_admin"
password = "{{ GRAFANA_DB_ADMIN_PASSWORD }}"
migration_locking = false

[remote_cache]
type = "redis"
connstr = "addr={{ CACHE_URL }},password={{ CACHE_AUTH }},db=0"

[plugins]
disable_plugins = ""

[auth]
signout_redirect_url = "https://{{ GRAFANA_URL }}/application/o/{{ OIDC_APPLICATION_SLUG }}/end-session/"
disable_login_form = false

[auth.anonymous]
enabled = false

[auth.generic_oauth]
enabled = true
client_id = "{{ GRAFANA_AUTHENTIK_CLIENT_ID }}"
client_secret = "{{ GRAFANA_AUTHENTIK_CLIENT_SECRET }}"
auth_url = "https://{{ OIDC_URL }}/application/o/authorize/"
token_url = "https://{{ OIDC_URL }}/application/o/token/"
api_url = "https://{{ OIDC_URL }}/application/o/userinfo/"
scopes = openid email profile groups offline_access
auto_login = true
# Optionally map user groups to Grafana roles
role_attribute_path = contains(groups[*], 'Homelab Admins') && 'Admin' || contains(groups[*], 'Grafana Editors') && 'Editor' || 'Viewer'
name_attribute_path = name
login_attribute_path = sub
allow_assign_grafana_admin = true
email_attribute_name = email
use_refresh_token = true

[users]
auto_assign_org = true
auto_assign_org_id = 1
