service:
  ui:
    type: NodePort
    nodePort: 30000
  manager:
    type: ClusterIP
longhornManager:
  log:
    format: json
longhornDriver:
  log:
    format: json
longhornUI:
  replicas: 3
  affinity:
    podAntiAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 1
          podAffinityTerm:
            labelSelector:
              matchExpressions:
                - key: app
                  operator: In
                  values:
                    - longhorn-ui
            topologyKey: kubernetes.io/hostname
  tolerations:
  - key: "CriticalAddonsOnly"
    value: "true"
    effect: "NoExecute"
  - key: "node-role.kubernetes.io/control-plane"
    operator: "Exists"
    effect: "NoSchedule"
  nodeSelector: {}
defaultSettings:
  defaultDataPath: "/var/lib/longhorn"
  deletingConfirmationFlag: "true"
enablePSP: false

persistence:
  defaultClassReplicaCount: 3
  dataEngine: v2

defaultBackupStore:
  backupTarget: "s3://longhorn@auto/"
  backupTargetCredentialSecret: "s3-secret-eso"

