### Official Link: https://artifacthub.io/packages/helm/longhorn/longhorn
global:
  nodeSelector:
    node-role.kubernetes.io/storage: 'true'

service:
  ui:
    type: Rancher-Proxy
    nodePort: null
  manager:
    type: ClusterIP
longhornManager:
  log:
    format: json
  nodeSelector:
    node-role.kubernetes.io/storage: 'true'
longhornDriver:
  log:
    format: json
  nodeSelector:
    node-role.kubernetes.io/storage: 'true'
longhornUI:
  replicas: 3
  affinity:
    podAntiAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 1
          podAffinityTerm:
            labelSelector:
              matchExpressions:
                - key: app
                  operator: In
                  values:
                    - longhorn-ui
            topologyKey: kubernetes.io/hostname
  nodeSelector:
    node-role.kubernetes.io/storage: 'true'
defaultSettings:
  defaultDataPath: "/dev/longhorn-v2-block"
  deletingConfirmationFlag: "true"
enablePSP: false

persistence:
  defaultClassReplicaCount: 3
  dataEngine: v2

defaultBackupStore:
  backupTarget: "s3://longhorn@auto/"
  backupTargetCredentialSecret: "s3-secret-eso"

