apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: argocd-secret-eso
  namespace: administrator-apps
spec:
  refreshInterval: 24h
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: argocd-secret-eso
    creationPolicy: Owner
    template:
      metadata:
        labels:
          app.kubernetes.io/part-of: argocd
  data:
    - secretKey: redis-password
      remoteRef:
        key: docker-secrets
        property: dragonflydb-credentials
    - secretKey: oidc.clientSecret
      remoteRef:
        key: docker-secrets
        property: argocd-oidc-client-secret

