services:
  main:
    image: traefik:${IMAGE_TAG}
    cap_add:
      - NET_ADMIN
    networks:
      traefik-internetwork:
        aliases:
          - traefik
    ports:
      - target: 80
        published: 80
        mode: host
      - target: 443
        published: 443
        mode: host
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.labels.codename == ${SWARM_NODE_CODENAME}
      resources:
        limits:
          cpus: "0.5"
          memory: "256M"
        reservations:
          cpus: "0.25"  
          memory: "64M"
      update_config:
        parallelism: 1
        delay: 5s
        failure_action: rollback
        max_failure_ratio: 0.5
      restart_policy:
        condition: any

    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ${DOCKER_BASED_DIR}/traefik/acme:/acme
      - ${DOCKER_BASED_DIR}/traefik/logs:/logs
      - ${DOCKER_BASED_DIR}/traefik/dynamic:/etc/traefik/dynamic
      - ${DOCKER_BASED_DIR}/traefik/traefik.yaml:/etc/traefik/traefik.yaml:ro
      - ${DOCKER_BASED_DIR}/traefik/.default-user.txt:/etc/traefik/default-user.txt:ro
    environment:
      - CF_API_EMAIL=${CF_API_EMAIL}
      - CF_API_KEY=${CF_API_KEY}
    
  healthcheck:
    image: "traefik/whoami"
    networks:
      - traefik-internetwork
    deploy:
      mode: global
      update_config:
        parallelism: 1
        delay: 5s
        failure_action: rollback
      restart_policy:
        condition: any
      placement:
        constraints:
          - node.platform.os == linux
      
networks:
  traefik-internetwork:
    external: true
