version: "3.1"
services:
  code-server:
    image: lscr.io/linuxserver/code-server:latest
    secrets:
      - code-server-password
    networks:
      - traefik-swarm-network
    deploy:
      mode: global
      placement:
        constraints:
          - node.role == worker
      restart_policy:
        condition: on-failure
      labels:
        # Frontend
        - traefik.enable=true
        - traefik.docker.network=traefik-swarm-network
        - "traefik.http.routers.code-server-http.entrypoints=web"
        - "traefik.http.routers.code-server-http.rule=Host(`code-server.mcbourdeux-workstation.com`)"
        - "traefik.http.routers.code-server-http.middlewares=code-server-https"
        - "traefik.http.routers.code-server-http.service=code-server"
        - "traefik.http.services.code-server.loadbalancer.server.port=8443"
        - "traefik.http.middlewares.code-server-https.redirectscheme.scheme=https"
        - "traefik.http.routers.code-server.entrypoints=websecure"
        - "traefik.http.routers.code-server.rule=Host(`code-server.mcbourdeux-workstation.com`)"
        - "traefik.http.routers.code-server.tls=true"
        - "traefik.http.routers.code-server.tls.certresolver=letsencrypt"
        - "traefik.http.services.code-server.loadbalancer.sticky.cookie=true"
        - "traefik.http.services.code-server.loadbalancer.sticky.cookie.name=code-server_ha"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - PASSWORD_FILE=/run/secrets/code-server-password
      - SUDO_PASSWORD_FILE=/run/secrets/code-server-password
      - PROXY_DOMAIN=code-server.mcbourdeux-workstation.com #optional
      - DEFAULT_WORKSPACE=/config/workspace #optional
    volumes:
      - /datacenter/docker/code-server:/config

networks:
  traefik-swarm-network:
    external: true

secrets:
  code-server-password:
    external: true
