services:
  dashboard:
    image: netbirdio/dashboard:${NETBIRD_DASHBOARD_TAG}
    networks:
      - traefik-internetwork
    environment:
      - NETBIRD_MGMT_API_ENDPOINT=https://${NETBIRD_DOMAIN}
      - NETBIRD_MGMT_GRPC_API_ENDPOINT=https://${NETBIRD_DOMAIN}
      - AUTH_AUDIENCE=netbird-dashboard
      - AUTH_CLIENT_ID=netbird-dashboard
      - AUTH_CLIENT_SECRET=
      - AUTH_AUTHORITY=https://${NETBIRD_DOMAIN}/oauth2
      - USE_AUTH0=false
      - AUTH_SUPPORTED_SCOPES=openid profile email groups
      - AUTH_REDIRECT_URI=/nb-auth
      - AUTH_SILENT_REDIRECT_URI=/nb-silent-auth
      - NGINX_SSL_PORT=443
      - LETSENCRYPT_DOMAIN=none
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.labels.codename == ${SWARM_NODE_CODENAME}
      restart_policy:
        condition: on-failure

  netbird-server:
    image: netbirdio/netbird-server:${NETBIRD_SERVER_TAG}
    networks:
      - traefik-internetwork
    ports:
      - target: 3478
        published: 3478
        protocol: udp
        mode: host
    volumes:
      - netbird-data:/var/lib/netbird
    configs:
      - source: netbird-config-yaml
        target: /etc/netbird/config.yaml
    command: ["--config", "/etc/netbird/config.yaml"]
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.labels.codename == ${SWARM_NODE_CODENAME}
      restart_policy:
        condition: on-failure

volumes:
  netbird-data:
    driver: local

networks:
  traefik-internetwork:
    external: true

configs:
  netbird-config-yaml:
    external: true
