apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: vault-backend
  namespace: kube-system
spec:
  provider:
    vault:
      server: https://vault.mcb-homelab.com
      path: kubernetes
      version: v2
      auth:
        kubernetes:
          mountPath: kubernetes
          role: eso-role
          serviceAccountRef:
            name: vault-auth
            namespace: kube-system
            audiences:
              - vault
          secretRef:
            name: vault-auth-token
            key: token
