---

services:
  authentik-postgresql:
    image: docker.io/library/postgres:16-alpine
    deploy:
      update_config:
        parallelism: 1
        delay: 5s
        failure_action: rollback
      replicas: 1
      resources:
        limits:
          cpus: "0.5"   
          memory: "1G"  
        reservations:
          cpus: "0.25"
          memory: "256M"
      restart_policy:
        condition: any
      placement:
        constraints:
          - node.platform.os == linux
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      start_period: 20s
      interval: 30s
      retries: 5
      timeout: 5s
    volumes:
      - authentik-db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${PG_PASS:?database password required}
      POSTGRES_USER: ${PG_USER:-authentik}
      POSTGRES_DB: ${PG_DB:-authentik}
    networks:
      - db-internetwork
  authentik-server:
    image: ${AUTHENTIK_IMAGE:-ghcr.io/goauthentik/server}:${AUTHENTIK_TAG:-2025.2.2}
    command: server
    environment:
      AUTHENTIK_REDIS__HOST: tasks.haproxy-redis
      AUTHENTIK_POSTGRESQL__HOST: authentik-postgresql
      AUTHENTIK_POSTGRESQL__USER: ${PG_USER:-authentik}
      AUTHENTIK_POSTGRESQL__NAME: ${PG_DB:-authentik}
      AUTHENTIK_POSTGRESQL__PASSWORD: ${PG_PASS}
      AUTHENTIK_SECRET_KEY: ${AUTHENTIK_SECRET_KEY}
    volumes:
      - authentik-server-media:/media
      - authentik-server-templates:/templates
    deploy:
      update_config:
        parallelism: 1
        delay: 5s
        failure_action: rollback
      replicas: 1
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - node.platform.os == linux
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.authentik.rule=Host(`${UI_URL}`)"
        - "traefik.http.routers.authentik.entrypoints=websecure"
        - "traefik.http.services.authentik-server.loadbalancer.server.port=9000"
        - "traefik.http.routers.authentik.service=authentik-server"
        - "traefik.http.routers.authentik.tls.certresolver=letsencrypt"
        - "traefik.http.services.authentik-server.loadbalancer.sticky.cookie=true"
        - "traefik.http.services.authentik-server.loadbalancer.sticky.cookie.name=authentik_ha"
    depends_on:
      - authentik-postgresql
      - redis
    networks:
      - traefik-internetwork
      - db-internetwork
  authentik-worker:
    image: ${AUTHENTIK_IMAGE:-ghcr.io/goauthentik/server}:${AUTHENTIK_TAG:-2025.2.2}
    command: worker
    environment:
      AUTHENTIK_REDIS__HOST: tasks.haproxy-redis
      AUTHENTIK_POSTGRESQL__HOST: authentik-postgresql
      AUTHENTIK_POSTGRESQL__USER: ${PG_USER:-authentik}
      AUTHENTIK_POSTGRESQL__NAME: ${PG_DB:-authentik}
      AUTHENTIK_POSTGRESQL__PASSWORD: ${PG_PASS}
      AUTHENTIK_SECRET_KEY: ${AUTHENTIK_SECRET_KEY}
    user: root
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - authentik-worker-media:/media
      - authentik-worker-certs:/certs
      - authentik-worker-templates:/templates
    depends_on:
      - authentik-postgresql
      - redis
    networks:
      - db-internetwork
      - traefik-internetwork
    deploy:
      update_config:
        parallelism: 1
        delay: 5s
        failure_action: rollback
      replicas: 1
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - node.platform.os == linux

networks:
  db-internetwork:
    external: true
  traefik-internetwork:
    external: true

volumes:
  authentik-db:
    external: true
  redis:
    external: true
  authentik-server-media:
    external: true
  authentik-server-templates:
    external: true
  authentik-worker-media:
    external: true
  authentik-worker-certs:
    external: true
  authentik-worker-templates:
    external: true
