version: "3.3"

services:
  portainer:
    image: portainer/portainer-ee:latest
    command: -H unix:///var/run/docker.sock
    container_name: portainer
    restart: always
    ports:
      - 9000:9000
    networks:
      - traefik-internetwork
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /datacenter/docker/portainer:/data
    labels:
      # Frontend
      - "traefik.enable=true"
      - "traefik.http.routers.portainer.rule=Host(`portainer2.mcbourdeux-workstation.com`)"
      - "traefik.http.routers.portainer.entrypoints=websecure"
      - "traefik.http.services.portainer.loadbalancer.server.port=9000"
      - "traefik.http.routers.portainer.service=portainer"
      - "traefik.http.routers.portainer.tls.certresolver=letsencrypt"

networks:
  traefik-internetwork:
    external: true
