apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: s3-secret-eso
  namespace: storageclass-system
spec:
  refreshInterval: 24h
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: s3-secret-eso
    creationPolicy: Owner
    deletionPolicy: Delete
  data:
    - secretKey: AWS_ACCESS_KEY_ID
      remoteRef:
        key: cloudflare-api
        property: r2_access_key
    - secretKey: AWS_ENDPOINTS
      remoteRef:
        key: cloudflare-api
        property: r2_endpoint
    - secretKey: AWS_SECRET_ACCESS_KEY
      remoteRef:
        key: cloudflare-api
        property: r2_secret_key
