version: "3.4"

services:
  mq:
    container_name: mq
    image: eclipse-mosquitto:2.0.11-openssl
    restart: unless-stopped
    hostname: mq
    volumes:
      - /datacenter/docker/mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf # need to pull conf file from github before running (under docker/mosquitto.conf)
      - /datacenter/docker/mosquitto/data:/mosquitto/data
      - /datacenter/docker/mosquitto/log:/mosquitto/log
      - /datacenter/docker/mosquitto/certs:/mosquitto/certs
    ports:
      - "127.0.0.1:1883:1883"
      - "8883:8883"
    expose:
      - "8883"
    networks:
      - traefik-internetwork
    labels:
      - traefik.enable=true
      - traefik.docker.network=traefik-internetwork
      - traefik.tcp.routers.mqtts.rule=HostSNI(`broker.NETMAKER_BASE_DOMAIN`)
      - traefik.tcp.routers.mqtts.tls.passthrough=true
      - traefik.tcp.services.mqtts-svc.loadbalancer.server.port=8883
      - traefik.tcp.routers.mqtts.service=mqtts-svc
      - traefik.tcp.routers.mqtts.entrypoints=websecure
      
  coredns:
    container_name: coredns
    image: coredns/coredns
    command: -conf /root/dnsconfig/Corefile
    depends_on:
      - netmaker
    restart: always
    networks:
      - traefik-internetwork
    volumes:
      - /datacenter/docker/core-dns:/root/dnsconfig

  netmaker: # The Primary Server for running Netmaker
    container_name: netmaker
    image: gravitl/netmaker:v0.14.2
    hostname: netmaker
    cap_add: 
      - NET_ADMIN
      - NET_RAW
      - SYS_MODULE
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1
      - net.ipv6.conf.all.disable_ipv6=0
      - net.ipv6.conf.all.forwarding=1
    restart: always
    networks:
      - postgres-infra
      - traefik-internetwork
    volumes: # Volume mounts necessary for sql, coredns, and mqtt
      - /datacenter/docker/netmaker/dnsconfig:/root/config/dnsconfig
      - /datacenter/docker/netmaker/data:/root/data
      - /datacenter/docker/netmaker/netmaker:/etc/netmaker
    environment: # Necessary capabilities to set iptables when running in container
      SERVER_NAME: "broker.${NETMAKER_BASE_DOMAIN}" # The domain/host IP indicating the mq broker address
      SERVER_HOST: "152.69.211.33" # Set to public IP of machine.
      SERVER_HTTP_HOST: "api-netmaker.${NETMAKER_BASE_DOMAIN}" # Overrides SERVER_HOST if set. Useful for making HTTP available via different interfaces/networks.
      SERVER_API_CONN_STRING: "api-netmaker.${NETMAKER_BASE_DOMAIN}:443"
      COREDNS_ADDR: "152.69.211.33" # Address of the CoreDNS server. Defaults to SERVER_HOST
      DNS_MODE: "on" # Enables DNS Mode, meaning all nodes will set hosts file for private dns settings.
      API_PORT: "8081" # The HTTP API port for Netmaker. Used for API calls / communication from front end. If changed, need to change port of BACKEND_URL for netmaker-ui.
      CLIENT_MODE: "on" # Depricated. CLIENT_MODE should always be ON
      REST_BACKEND: "on" # Enables the REST backend (API running on API_PORT at SERVER_HTTP_HOST). Change to "off" to turn off.
      DISABLE_REMOTE_IP_CHECK: "off" # If turned "on", Server will not set Host based on remote IP check. This is already overridden if SERVER_HOST is set. Turned "off" by default.
      TELEMETRY: "on" # Whether or not to send telemetry data to help improve Netmaker. Switch to "off" to opt out of sending telemetry.
      RCE: "off" # Enables setting PostUp and PostDown (arbitrary commands) on nodes from the server. Off by default.
      MASTER_KEY: "${NETMAKER_MASTER_KEY}" # The admin master key for accessing the API. Change this in any production installation.
      CORS_ALLOWED_ORIGIN: "*" # The "allowed origin" for API requests. Change to restrict where API requests can come from.
      DISPLAY_KEYS: "on" # Show keys permanently in UI (until deleted) as opposed to 1-time display.
      DATABASE: "postgres" # Database to use - sqlite, postgres, or rqlite
      SQL_HOST: "${POSTGRES_ROOT_USER}"
      SQL_PORT: "5432"
      SQL_DB: "${POSTGRES_DB}"
      SQL_USER: "${NETMAKER_USER}"
      SQL_PASS: "${NETMAKER_USER_PASSWORD}"
      NODE_ID: "netmaker-server" # used for HA - identifies this server vs other servers
      MQ_HOST: "mq"  # the address of the mq server. If running from docker compose it will be "mq". Otherwise, need to input address. If using "host networking", it will find and detect the IP of the mq container.
      MQ_ADMIN_PASSWORD: "Master21091996"
      MQ_PORT: "443" # the reachable port of MQ - change if external MQ port changes (port on proxy, not necessarily the one exposed in docker-compose)
      HOST_NETWORK: "off" # whether or not host networking is turned on. Only turn on if configured for host networking (see docker-compose.hostnetwork.yml). Will set host-level settings like iptables.
      VERBOSITY: "1" # logging verbosity level - 1, 2, or 3
      MANAGE_IPTABLES: "on" # deprecated
      PORT_FORWARD_SERVICES: "dns"
    ports:
      - "51821-51830:51821-51830/udp" # wireguard ports

    labels: # only for use with traefik proxy (default)
      - traefik.enable=true
      - traefik.docker.network=traefik-internetwork
      - traefik.http.routers.netmaker-api.entrypoints=websecure
      - traefik.http.routers.netmaker-api.tls.certresolver=letsencrypt
      - traefik.http.routers.netmaker-api.rule=Host(`api-netmaker.${NETMAKER_BASE_DOMAIN}`)
      - traefik.http.routers.netmaker-api.service=netmaker-api
      - traefik.http.services.netmaker-api.loadbalancer.server.port=8081

  netmaker-ui:  # The Netmaker UI Component
    container_name: netmaker-ui
    image: gravitl/netmaker-ui:v0.14.2
    hostname: netmaker-ui
    depends_on:
      - netmaker
    links:
      - "netmaker:api"
    restart: always
    networks:
      - traefik-internetwork
    environment:
      BACKEND_URL: "https://api-netmaker.${NETMAKER_BASE_DOMAIN}" # URL where UI will send API requests. Change based on SERVER_HOST, SERVER_HTTP_HOST, and API_PORT
    labels:
      - traefik.enable=true
      - traefik.docker.network=traefik-internetwork
      - traefik.http.middlewares.nmui-security.headers.accessControlAllowOriginList=*.${NETMAKER_BASE_DOMAIN}
      - traefik.http.middlewares.nmui-security.headers.stsSeconds=31536000
      - traefik.http.middlewares.nmui-security.headers.browserXssFilter=true
      - traefik.http.middlewares.nmui-security.headers.customFrameOptionsValue=SAMEORIGIN
      - traefik.http.middlewares.nmui-security.headers.customResponseHeaders.X-Robots-Tag=none
      - traefik.http.middlewares.nmui-security.headers.customResponseHeaders.Server= # Remove the server name
      - traefik.http.routers.netmaker-ui.entrypoints=websecure
      - traefik.http.routers.netmaker-ui.tls.certresolver=letsencrypt
      - traefik.http.routers.netmaker-ui.middlewares=nmui-security@docker
      - traefik.http.routers.netmaker-ui.rule=Host(`netmaker.${NETMAKER_BASE_DOMAIN}`)
      - traefik.http.routers.netmaker-ui.service=netmaker-ui
      - traefik.http.services.netmaker-ui.loadbalancer.server.port=80

networks:
  traefik-internetwork:
    external: true
  postgres-infra:
    external: true
