services:
  portainer:
    image: portainer/portainer-ee:latest
    container_name: portainer-prd-01
    command: -H unix:///var/run/docker.sock
    restart: always
    networks:
      - traefik-internetwork
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer-data:/data
    labels:
      # Frontend
      - "traefik.enable=true"
      - "traefik.http.routers.portainer.rule=Host(`${UI_URL}`)"
      - "traefik.http.routers.portainer.entrypoints=websecure"
      - "traefik.http.services.portainer.loadbalancer.server.port=9000"
      - "traefik.http.routers.portainer.service=portainer"
      - "traefik.http.routers.portainer.tls.certresolver=letsencrypt"
      - "traefik.http.services.portainer.loadbalancer.sticky.cookie=true"
      - "traefik.http.services.portainer.loadbalancer.sticky.cookie.name=portainer_ha"

volumes:
  portainer-data:
    external: true

networks:
  traefik-internetwork:
    external: true
