version: "3.8"

services:
  adguard:
    image: adguard/adguardhome:latest
    networks:
      - traefik-internetwork
    ports:
    - published: 53
      target: 53
      protocol: udp
    - published: 53
      target: 53
      protocol: tcp
    volumes:
      - adguard-work:/opt/adguardhome/work
      - adguard-config:/opt/adguardhome/conf

volumes:
  adguard-work:
    driver: local
  adguard-config:
    driver: local

networks:
  traefik-internetwork:
    external: true
